jobs:
  build:
    working_directory: ~/bego
    docker:
      - image: circleci/elixir:1.6-node-browsers
      - image: postgres:10
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          - v1-mix-cache-{{ .Branch }}
          - v1-mix-cache
      - restore_cache:
          keys:
          - v1-build-cache-{{ .Branch }}
          - v1-build-cache
      - restore_cache:
          keys:
            - v2-yarn-cache-{{ .Branch }}-{{ checksum "assets/yarn.lock" }}
            - v2-yarn-cache-{{ .Branch }}
            - v2-yarn-cache
      - run: mix local.hex --force
      - run: mix local.rebar
      - run:
          name: Fetching backend dependencies
          command: mix deps.get
      - run:
          name: Fetching frontend dependencies
          command: mix yarn
      - run:
          name: Running backend tests
          command: mix test
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"
      - save_cache:
          key: v2-yarn-cache-{{ .Branch }}-{{ checksum "assets/yarn.lock" }}
          paths:
            - assets/node_modules
            - ~/.yarn-cache
      - save_cache:
          key: v2-yarn-cache-{{ .Branch }}
          paths:
            - assets/node_modules
            - ~/.yarn-cache
      - save_cache:
          key: v2-yarn-cache
          paths:
            - assets/node_modules
            - ~/.yarn-cache

  deploy-production:
    working_directory: ~/bego
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Run setup script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4"
      - run:
          name: Deploy Master to Heroku Production
          command: |
            git push --force git@heroku.com:$HEROKU_PRODUCTION_APP.git HEAD:refs/heads/master
            heroku run "POOL_SIZE=2 mix ecto.migrate" --app $HEROKU_PRODUCTION_APP
            heroku restart --app $HEROKU_PRODUCTION_APP

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: master
