jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v3-yarn-cache-{{ .Branch }}
            - v3-yarn-cache
      - run:
          name: Fetching frontend dependencies
          command: yarn
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Write good
          command: yarn write-good
      - save_cache:
          key: v3-yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.yarn-cache
      - save_cache:
          key: v3-yarn-cache-{{ .Branch }}
          paths:
            - node_modules
            - ~/.yarn-cache
      - save_cache:
          key: v3-yarn-cache
          paths:
            - node_modules
            - ~/.yarn-cache

  deploy-production:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Heroku Production
          command: |
            git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION_APP.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: master
